### PR TITLE
Search Button Bug(Fixed it for Wrong input)

### PR DESCRIPTION
**Pull request by VanshChitransh**

### CODE REVIEW

**Comment by MohamedDanis** [comment]
give clear description of what you have done @VanshChitransh  and I have added pull request template in root. please check it

**Comment by MohamedDanis** [comment]
@VanshChitransh  build has failed. Please check and push again

**Comment by MohamedDanis** [comment]
also remember to pull the latest code

**Comment by VanshChitransh** [comment]
@MohamedDanis I am working on it.

**Comment by VanshChitransh** [comment]
@MohamedDanis Is the issue still there? I think @imkurosaki has already solved it.

**Comment by MohamedDanis** [comment]
oh yes, it's already fixed.So I will be closing this PR

**Pull request closed without merging**
