### PR TITLE
Feature: Added star count and fork count to repo card

### PR DESCRIPTION
**Pull request by akshayxml**
## Description
This pull request enhances the display of the Repo Card by adding the fork count and star count alongside the existing open issue count. This provides users with a more comprehensive overview of a repository's popularity and activity. It also refactors the code slightly, by adding a separate file for the icons.

## Motivation and Context
Previously, the repository information only displayed the open issue count. While this is useful, it doesn't provide a complete picture of a repository's engagement. Adding the fork count and star count offers valuable insights into:

* **Popularity:** The star count indicates how many users have shown interest in the repository.
* **Community engagement:** The fork count reflects how many users have created copies of the repository, potentially contributing to its development or using it as a basis for their own projects.

By including these additional metrics, users can gain a better understanding of a repository's overall health and activity level. This can help them make more informed decisions about whether to use, contribute to, or follow a particular repository.

## Screenshots:
Screenshot 2024-10-06 at 1 13 37 PM

### CODE REVIEW

**Review by MohamedDanis — APPROVED** [review]

**Comment by MohamedDanis** [comment]
I will be merging this(because I found it cool) . Note that, you should open an issue before you start on the code. Thank you for your contributions

**Comment by MohamedDanis** [comment]
Make sure you have pulled the latest code. And let me know

**Comment by akshayxml** [comment]
@MohamedDanis sorry was having some issue with the branches, have fixed them and have pulled the latest code.

Sure, will open issue from next time.

**Review by MohamedDanis — APPROVED** [review]

**Comment by MohamedDanis** [comment]
found an issue, when clicked on star or fork, it redirects to issues page @akshayxml 

### ScreenRecording
https://jam.dev/c/c0e8162d-0641-4bcd-a250-85a1bf31c573

**Comment by akshayxml** [comment]
@MohamedDanis fixed

**Comment by MohamedDanis** [comment]
@all-contributors please add @akshayxml  for code

**Pull request merged**
