### PR TITLE
bug:Add Language indication in card #24

### PR DESCRIPTION
**Pull request by LeninKhangjrakpam**
Fixed: No Language indication in repository card  Issue #23

## Description
Add Language label to card

## Motivation and Context
Allow user to know which language the card belongs to, when doing multiple language search

Issue: #23

## How Has This Been Tested?
- Manual Testing in various browser

## Screenshots:
image

### CODE REVIEW

**Comment by MohamedDanis** [comment]
Screenshot 2024-10-14 111053
how about position it over right side ?

**Comment by LeninKhangjrakpam** [comment]
@MohamedDanis take a look at this.

image

**Comment by MohamedDanis** [comment]
make a push with the above design, I will review it

**Comment by MohamedDanis** [comment]
make  svg height and width to 25

**Comment by MohamedDanis** [comment]
congratulations on your pr merged @LeninKhangjrakpam

**Comment by MohamedDanis** [comment]
@all-contributors please add @LeninKhangjrakpam  for code

**Comment by MohamedDanis** [comment]
Don't forget to star the repo

**Pull request merged**
