### PR TITLE
Make tags clickable

### PR DESCRIPTION
**Pull request by Joshi-Sarthak**
## Description

This PR makes the tags in individual repo cards clickable. Now, clicking on a tag will initiate a search for that topic.

## Motivation and Context

This makes for a better and faster user experience

## Screenshots:
Screenshot 2024-10-02 174646

Left: Tag in normal state
Right: Tag changes color when hovered over

### CODE REVIEW

**Comment by MohamedDanis** [comment]
@Joshi-Sarthak there is some issue in it, the selected topic should be passed to topic ,not to languages in query constant.Please solve it and push again

**Comment by Joshi-Sarthak** [comment]
Have I understood the flow correctly, please correct me if i am wrong:
Clicking on a topic initiates a search for both the topic and its associated language.

**Comment by MohamedDanis** [comment]
code

there is a topic field in above constant called 'query',the topics should be passed there
When you solve it , remember to pull the latest code

**Comment by MohamedDanis** [comment]
build failed, please check and solve it. Please check latest code has been pulled

**Comment by MohamedDanis** [comment]
Please check, build has failed

**Pull request closed without merging**
