### PR TITLE
Add functionality that links the clickable issues count to the respective repository's GitHub issues page

### LINKED ISSUE #28: clicking on issues count should redirect user to the issues page of the repository
Discription: Currently, the issues count displayed is clickable, but it does not redirect user to anywhere. To improve user experience, this needs to be enhanced so that clicking on the issues count takes the user to the respective repository's GitHub issues page.

image

### PR DESCRIPTION
**Pull request by HalfToothed**
## Description
This PR adds functionality that on clicking the issues count user gets redirected to the respective repository's GitHub issues page
closes #28 

## Motivation and Context
This change is necessary to enhance user experience by making the clickable issues count functional.

### CODE REVIEW

**Comment by MohamedDanis** [comment]
make the icon clickable too

**Comment by HalfToothed** [comment]
@MohamedDanis  adding the same action to the icon doesn’t add much value and can clutter the interface, because the issue count text is already clickable 

Icon here is used as visual indicator, that's why we should not make the icon clickable

Please tell me what are your views on it.

**Comment by MohamedDanis** [comment]
Ok,we can proceed with the current change

**Review by MohamedDanis — APPROVED** [review]

**Comment by MohamedDanis** [comment]
@all-contributors please add @HalfToothed  for code

**Pull request merged**
